import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "coverage/**",
  ]),
  {
    // These files are generated by the shadcn CLI and vendored from shadcn/ui
    // (MIT) — see NOTICE. Upstream has not yet adopted the React 19 compiler
    // hook rules, and editing them here would be silently reverted the next
    // time `shadcn add` is run. Suppress the single offending rule rather than
    // forking vendored code; first-party source stays strict.
    files: ["components/ui/**/*.tsx", "hooks/use-mobile.ts"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
])

export default eslintConfig
